---
- name: Set location of Podman Play Manifest
  ansible.builtin.set_fact:
    kube_play_file: >-
      {{ tpa_single_node_kube_manifest_dir + '/Deployments/' + podman_spec.kube_file_content.metadata.namespace + '_'
      + podman_spec.kube_file_content.metadata.name + '.yaml' }}

- name: Copy Manifest to Server
  ansible.builtin.copy:
    content: "{{ podman_spec.kube_file_content | to_nice_yaml(indent=2) }}"
    dest: "{{ kube_play_file }}"
    mode: "0600"
  register: copy_manifest

- name: Copy Systemd file to Server
  ansible.builtin.template:
    src: systemd/systemd-cronjob.j2
    dest: "{{ tpa_single_node_systemd_directory + '/' + podman_spec.systemd_file }}.service"
    mode: "0600"
  register: copy_systemd_file

- name: Copy Systemd file timer to Server
  ansible.builtin.template:
    src: systemd/systemd-timer-{{ podman_spec.timer_type }}.j2
    dest: "{{ tpa_single_node_systemd_directory + '/' + podman_spec.systemd_file }}.timer"
    mode: "0600"
  register: copy_systemd_timer_file

- name: Restart Podman Service
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: false
    name: "{{ podman_spec.systemd_file }}"
    no_block: true
  when: copy_manifest.changed or copy_systemd_file.changed

- name: Restart Timer Podman Service
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: false
    name: "{{ podman_spec.systemd_file }}.timer"
    no_block: true
  when: copy_manifest.changed or copy_systemd_timer_file.changed
