#!/bin/bash

SUBJ='/C=XX/ST=Test State/L=Test Town'
SUBJ+='/O=Test Organization/OU=Test Organization Unit'
SUBJ+='/CN=John Test/emailAddress=jtest@test.org'

CERTS=(
    'guac-collectsub-tls-certificate'
    'guac-graphql-tls-certificate'
    'collector-osv-tls-certificate'
    'collector-osv-tls-client-certificate.crt'
    'collectorist-api-tls-certificate'
    'collectorist-api-tls-csub-certificate.crt'
    'spog-api-tls-certificate'
    'spog-ui-tls-certificate'
)

rm -f *.key *.pem *.crt
for certname in "${CERTS[@]}"; do
    keyname="${certname%.*}.key"
    if [[ "${certname}" != *.pem && "${certname}" != *.crt ]]; then
        certname+='.pem'
    fi
    openssl genrsa -out "${keyname}" 4096
    openssl req -new -x509 -subj "${SUBJ}" -days 365 -key "${keyname}" -out "${certname}"
done
