# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    #config.registration.username = '<your Red Hat username>'
    #config.registration.password = '<your Red Hat password>'
    config.registration.username = ENV['TPA_SINGLE_NODE_REGISTRY_USERNAME']
    config.registration.password = ENV['TPA_SINGLE_NODE_REGISTRY_PASSWORD']

    config.vm.define "trustification" do |main_server|
          main_server.vm.box = "generic-x64/rhel9"
          #main_server.vm.box = "fedora/40-cloud-base"
          main_server.vm.hostname = "trustification"
          main_server.vm.network "private_network", ip: "192.168.121.60"
          main_server.vm.network "forwarded_port", guest: 80, host: 8080

          main_server.vm.provider "libvirt" do |libvirt|
              libvirt.memory = "4096"
              libvirt.cpus = "2"
              # libvirt.qemu_use_session = "false"
          end

          main_server.vm.provision "ansible" do |ansible|
             ansible.verbose = "vvvv"
             ansible.compatibility_mode = "2.0"
             ansible.playbook = "./../../play.yml"
             ansible.galaxy_role_file = "./../../requirements.yml"
             #ansible.galaxy_command = "ansible-galaxy collection install -r %{role_file}"
           end
      end

end
