FROM {{ tpa_single_node_trustification_image }}

RUN microdnf install cronie -y

COPY v11-walker /etc/cron.d/v11-walker

RUN chmod 0644 /etc/cron.d/v11-walker

RUN crontab /etc/cron.d/v11-walker

CMD crond -n
